#include "doc.h"

int main()
{
    stack stk =  {'\0'};
    stkconstructor(&stk, 2);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpush(&stk, 10);
    stkpush(&stk, 20);
    stkpush(&stk, 30);
    stkpush(&stk, 40);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stkpop(&stk);
    stackdistructor(&stk);
    fclose (logfile);
    FILE* textcode = fopen("textcode.txt", "r");
    FILE* numericalcode = fopen("numericalcode.txt", "w");
    translator(textcode, numericalcode);
    fclose(textcode);
    return 0;
}



